#!/bin/bash

BOARDS=$(bin/arduino-cli board list)

echo "$BOARDS"

# cancel if no board
if [[ "$BOARDS" != *"COM"* ]]; then
    echo "No board detected. Cancelled."
    exit 1
fi


# AUTO PORT 
COMPORT=$(echo "$BOARDS" | tail -n +2 | awk '{print $1}')
echo "Auto port: $COMPORT"

# MANUAL PORT
# read -p "Enter COM port: " COMPORT

./verify
bin/arduino-cli upload -p "$COMPORT" --fqbn arduino:avr:nano MeguClock/MeguClock.ino -v