name=Modified DS3231 for MEGU-CLOCK
version=0.6.7
author=Ichimaki Kasura
maintainer=Ichimaki Kasura <ichimakikasura@gmail.com>
sentence=Custom DS3231 for MEGUCLOCK
paragraph=Custom DS3231 for MEGUCLOCK