name=Modified ST7735 for MEGU-CLOCK
version=0.6.7
author=Ichimaki Kasura
maintainer=Ichimaki Kasura <ichimakikasura@gmail.com>
sentence=Custom ST7735 for MEGUCLOCK
paragraph=Custom ST7735 for MEGUCLOCK